name: Build APK (p4a direct)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installer dépendances Android
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk python3 python3-pip git unzip zip wget curl build-essential ccache

      - name: Installer Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools
          sudo mv cmdline-tools /usr/lib/android-sdk
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "platform-tools" "build-tools;34.0.0"

      - name: Installer Python-for-Android (p4a)
        run: |
          python3 -m pip install --upgrade pip
          pip install python-for-android==2024.1.21

      - name: Construire l'APK avec p4a
        run: |
          mkdir -p dist
          export ANDROIDSDK=/usr/lib/android-sdk
          export ANDROIDNDK=$ANDROIDSDK/ndk-bundle
          export PATH=$ANDROIDSDK/platform-tools:$PATH
          p4a apk \
            --private . \
            --package org.bibliotheque.app \
            --name "BibliothequeApp" \
            --version 1.0 \
            --bootstrap sdl2 \
            --requirements=python3,kivy \
            --android-api 33 \
            --arch=armeabi-v7a \
            --output-filename BibliothequeApp.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BibliothequeApp
          path: BibliothequeApp.apk
